<!-- Copyright (c) <2012>, <Go Daddy Operating Company, LLC>
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 -->
<li sort="<?php echo $this->currentSort; ?>" class="activity">
	<h2 class="expanded"><span class="sum">New Activity:</span><span class="delete"></span></h2>
	<div>
		<div class="wizardFormInput">
			<label>Summary</label>
			<input type="text" class="activitySummary" size="80"/>
		</div><br clear="all" />
		<div class="wizardFormInput">
			<label>Deadline (in minutes):</label>
			<input type="text" class="activityDeadline" value="0" />
		</div>
		<div class="wizardFormInput">
			<label>Deadline Type:</label>
			<select class="activityDeadlineType">
				<?php foreach ($this->deadlineTypeList as $deadlineType): ?>
				<option value="<?php echo $deadlineType->AtulDeadlineTypeID; ?>"><?php echo $deadlineType->DeadlineName; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div class="wizardFormInput">
			<label>Fail when Deadline Exceeded:</label>
			<input type="checkbox" class="activityMissedWhenExceeded" />
		</div>
	</div>
	<div class="wizardFormLine">
		<div class="wizardFormTextBoxSmall">
			<label>Description:</label>
			<textarea class="activityDescription"></textarea>
		</div>
		<div class="wizardFormTextBoxSmall">
			<label>Procedure:</label>
			<textarea class="activityProcedure"></textarea>
		</div>
	</div><br clear="all" />
</li>